id: PEA552C83
initial_creation_type: input
source_metadata:
  Title: Vajrayāna darśana mīmāṁsā
  Editor: '-'
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  Vajrayāna darśana mīmāṁsā:
    Text Version: Romanized
    Input Personnel: Bibek Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:17:58.029168'
last_modified_at: '2022-03-08T17:17:58.029177'
